// Generated by Selenium IDE
package edu.pitt.cs;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;
import org.junit.After;
import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.chrome.ChromeOptions;



@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        driver = new ChromeDriver(options);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tEST2RESET() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Reset\']")).click();
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[1]"))
                .getText(),
            is("ID 1. Jennyanydots")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[2]"))
                .getText(),
            is("ID 2. Old Deuteronomy")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[3]"))
                .getText(),
            is("ID 3. Mistoffelees")
        );
    }

    

    

    @Test
    public void tEST1LINKS() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        {
            List<WebElement> elements = driver.findElements(
                By.xpath(
                    "//a[text()=\'Reset\' and contains(@href, \'/reset\')]"
                )
            );
            assert (elements.size() > 0);
        }
    }


    @Test
    public void tEST4LISTING() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Catalog\']")).click();
        vars.put(
            "count",
            driver.findElements(By.xpath("//div[@id=\'listing\']//li")).size()
        );
        assertEquals(vars.get("count").toString(), "3");
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[3]"))
                .getText(),
            is("ID 3. Mistoffelees")
        );
    }

    @Test
    public void tEST3CATALOG() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Catalog\']")).click();
        {
            List<WebElement> elements = driver.findElements(
                By.xpath("//li[2]/img[contains(@src, \'/images/cat2.jpg\')]")
            );
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tEST5RENTACAT() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Rent-A-Cat\']")).click();
        {
            List<WebElement> elements = driver.findElements(
                By.xpath("//button[text()=\'Rent\']")
            );
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(
                By.xpath("//button[text()=\'Return\']")
            );
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tEST6RENT() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Rent-A-Cat\']")).click();
        driver.findElement(By.xpath("//input[@id=\"rentID\"]")).sendKeys("1");
        driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[1]"))
                .getText(),
            is("Rented out")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[2]"))
                .getText(),
            is("ID 2. Old Deuteronomy")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[3]"))
                .getText(),
            is("ID 3. Mistoffelees")
        );
        assertThat(
            driver.findElement(By.xpath("//div[@id=\"rentResult\"]")).getText(),
            is("Success!")
        );
    }

    @Test
    public void tEST8FEEDACAT() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Feed-A-Cat\']")).click();
        {
            List<WebElement> elements = driver.findElements(
                By.xpath("//button[text()=\'Feed\']")
            );
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tEST7RETURN() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Rent-A-Cat\']")).click();
        driver.findElement(By.xpath("//input[@id=\'returnID\']")).sendKeys("2");
        driver.findElement(By.xpath("//button[text()=\'Return\']")).click();
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[1]"))
                .getText(),
            is("ID 1. Jennyanydots")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[2]"))
                .getText(),
            is("ID 2. Old Deuteronomy")
        );
        assertThat(
            driver
                .findElement(By.xpath("(//div[@id=\'listing\']//li)[3]"))
                .getText(),
            is("ID 3. Mistoffelees")
        );
        assertThat(
            driver
                .findElement(By.xpath("//div[@id=\'returnResult\']"))
                .getText(),
            is("Success!")
        );
    }

    @Test
    public void tEST9FEED() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Feed-A-Cat\']")).click();
        driver.findElement(By.xpath("//input[@id=\'catnips\']")).sendKeys("6");
        driver.findElement(By.xpath("//button[text()=\'Feed\']")).click();
        {
            WebDriverWait wait = new WebDriverWait(
                driver,
                Duration.ofSeconds(2)
            );
            wait.until(
                ExpectedConditions.presenceOfElementLocated(
                    By.xpath(
                        "//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']"
                    )
                )
            );
        }
        assertThat(
            driver.findElement(By.xpath("//*[@id=\'feedResult\']")).getText(),
            is("Nom, nom, nom.")
        );
    }

    @Test
    public void tEST10GREETACAT() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.findElement(By.xpath("//a[text()=\'Greet-A-Cat\']")).click();
        assertThat(
            driver.findElement(By.xpath("//div[@id=\"greeting\"]")).getText(),
            is("Meow!Meow!Meow!")
        );
    }

    @Test
    public void tEST11GREETACATWITHNAME() {
        driver.get("http://localhost:8080/");
        js.executeScript(
            "document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";"
        );
        driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
        assertThat(
            driver.findElement(By.xpath("//div[@id=\'greeting\']")).getText(),
            is("Meow! from Jennyanydots.")
        );
    }
}
